# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3_master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pwm_control_0_0/design_1_pwm_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_control_0_0 || ORIG_REF_NAME==design_1_pwm_control_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_machine_0_0/design_1_state_machine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_machine_0_0 || ORIG_REF_NAME==design_1_state_machine_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pwm_control_0_1/design_1_pwm_control_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_control_0_1 || ORIG_REF_NAME==design_1_pwm_control_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_0/design_1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_0 || ORIG_REF_NAME==design_1_xlslice_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_quadratur_decoder_0_4/design_1_quadratur_decoder_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_quadratur_decoder_0_4 || ORIG_REF_NAME==design_1_quadratur_decoder_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_quadratur_decoder_0_5/design_1_quadratur_decoder_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_quadratur_decoder_0_5 || ORIG_REF_NAME==design_1_quadratur_decoder_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_2/design_1_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_2 || ORIG_REF_NAME==design_1_xlconcat_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_3/design_1_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_3 || ORIG_REF_NAME==design_1_xlconcat_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_delay_0_0/design_1_delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_delay_0_0 || ORIG_REF_NAME==design_1_delay_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_4_8/design_1_xlslice_4_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_8 || ORIG_REF_NAME==design_1_xlslice_4_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_5_0/design_1_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_0 || ORIG_REF_NAME==design_1_xlslice_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_5_1/design_1_xlslice_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_1 || ORIG_REF_NAME==design_1_xlslice_5_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_5_2/design_1_xlslice_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_2 || ORIG_REF_NAME==design_1_xlslice_5_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Evenparity_0_0/design_1_Evenparity_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Evenparity_0_0 || ORIG_REF_NAME==design_1_Evenparity_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_parity_check_0/design_1_parity_check_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_parity_check_0 || ORIG_REF_NAME==design_1_parity_check_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_2_0/design_1_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_2_0 || ORIG_REF_NAME==design_1_xlconcat_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_0_1/design_1_SPI_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_0_1 || ORIG_REF_NAME==design_1_SPI_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_JB6_0/design_1_JB6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_JB6_0 || ORIG_REF_NAME==design_1_JB6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_JB6_1/design_1_JB6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_JB6_1 || ORIG_REF_NAME==design_1_JB6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_3_1/design_1_xlconcat_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_3_1 || ORIG_REF_NAME==design_1_xlconcat_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_motor_controler_0_0/design_1_motor_controler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_motor_controler_0_0 || ORIG_REF_NAME==design_1_motor_controler_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_motor_controler_0_1/design_1_motor_controler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_motor_controler_0_1 || ORIG_REF_NAME==design_1_motor_controler_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_delay_0_1/design_1_delay_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_delay_0_1 || ORIG_REF_NAME==design_1_delay_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_delay_1_0/design_1_delay_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_delay_1_0 || ORIG_REF_NAME==design_1_delay_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_enable_0_0/design_1_enable_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_enable_0_0 || ORIG_REF_NAME==design_1_enable_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_enable_1_0/design_1_enable_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_enable_1_0 || ORIG_REF_NAME==design_1_enable_1_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
